name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [ opened, reopened, synchronize ]
    path-ignores:
      - 'CHANGELOG.md'
      - 'RELEASE.md'

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
